# Enviroment variables:
# $FIREBASE_TOKEN

version: 2.1

executors:
  nodejs:
    docker:
      - image: node:lts
    working_directory: /home/circleci/app
jobs:
  build:
    executor: nodejs
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/app
      - run:
          name: Install
          command: npm ci
      - run:
          name: Build
          command: npm run build
  tests:
    executor: nodejs
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/app
      - run:
          name: Install
          command: npm ci
      - run:
          name: Run tests
          command: npm test
  deploy:
    executor: nodejs
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/app
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  version: 2.1
  react:
    jobs:
      - build
      - tests:
          requires:
              - build
      - deploy:
          requires:
              - tests
          filters:
            branches:
              only:
                - master